### ISSUE TITLE
Graphs: not working in zabbix 1.8.5

### ISSUE THREAD

**Issue by mattiasgeniar** [mattiasgeniar/MoZBX#16]
to be verified.

**Comment by mattiasgeniar** [comment]
They're working on my system, if anyone is experiencing this issue, please tell me if you see any output in the error log (both from the mobile zabbix & real zabbix system).

**Comment by fjrial** [comment]
Hi:

I've lighttpd as web server for zabbix frontend. Installed mozbx and noticed that mobile app does not show the images generated from zabbix.. (lighttpd error 417 on log)

To fix this, add this line in class_zabbix.php in line 495

curl_setopt($ch, CURLOPT_HTTPHEADER, array('Expect:'));

**Comment by mattiasgeniar** [comment]
Thanks for reporting, committed.
