### ISSUE TITLE
Self hosted authentication fails

### ISSUE THREAD

**Issue by denydias** [mattiasgeniar/MoZBX#19]
First things first: many thanks for this little app, Mattias!

I've just installed MoZBX on my own server. It's the same server where Zabbix itself is installed. Seems that is something wrong. Look the details bellow:
- From my notebook's command line:
  $ curl -i -X POST -H 'Content-Type: application/json' -d '{"params": {"password": "pass", "user": "user"}, "jsonrpc": "2.0", "method": "user.authenticate"}' http://zabbix.bogus.com/api_jsonrpc.php
  HTTP/1.0 200 OK
  X-Powered-By: PHP/5.3.3-7+squeeze3
  Content-Type: application/json
  Set-Cookie: zbx_sessionid=ea0b4816d4b7a69c1fdb8610780d8f72
  Set-Cookie: zbx_sessionid=ea0b4816d4b7a69c1fdb8610780d8f72
  Date: Sat, 30 Jul 2011 07:06:02 GMT
  Server: lighttpd/1.4.28
  X-Cache: MISS from localhost
  X-Cache-Lookup: MISS from localhost:80
  Via: 1.0 localhost (squid/3.1.6)
  Connection: close
- From MoZBX:
  After access the application and type the correct credentials, it just reload to the homepage. No output on Lighttpd logs. After enable jason logs on config.php, there is:
  ======= 2011/07/30, 04:16:13 =======
  Source IP: ###.###.###.###
  Action: user.authenticate
  Request: 
  '{"auth":false,"method":"user.authenticate","id":1,"params":{"user":"user","password":"pass"},"jsonrpc":"2.0"}'

Response: 
# false

I'm stuck here. Any advices? Btw, my server meets all requirements at http://www.mozbx.net/install-apache.html, except it uses Lighttpd, not Apache. This shouldn't be an issue, does it?

**Comment by mattiasgeniar** [comment]
Lighttpd should work just as well, I'll assume your parsing it via fast-cgi or php-fpm?

Does the authentication work if you try it from the hosted version, at http://app.mozbx.net? Just to exclude zabbix server itself.

Furthermore:
- what version of zabbix server are you running?
- do you have any kind of iptables active?
- do you run selinux/apparmor to limit what lighttpd may do?
- if you set your lighttpd logs to be more  verbose, can you see any error logs at all?

**Comment by denydias** [comment]
Hi Mattias,

After your reply I get on the job to check that stuff you asked and I realized that it works when it's not going through squid. Is there something on the cache properties at squid preventing the API URL bypass as it should be. If I set the URL to the server IP (bypassing squid) it works. When I set it to the name, which makes the web traffic be handled by squid, it fails. I'll review and fix this.  I let you know as soon as I find the proper squid settings, as others could have a similar setup and this information could be useful for them.

**Comment by mattiasgeniar** [comment]
Hi,

Great find, I'm curious to know what is causing Squid to cache the request. Since we're faking HTTP requests, it could be that my curl request(s) need extra headers to be sent along. I've just read on the Zabbix Forum (http://www.zabbix.com/forum/showthread.php?t=19322&page=4) that someone else needed to add the Expect-header to get it to work properly.

I'll review that later on (see how it still works on apache stuff) and commit it later.
