### ISSUE TITLE
Zabbix 1.8.7 - API Failed Authentication

### ISSUE THREAD

**Issue by mattcadorette** [mattiasgeniar/MoZBX#25]
When I try to login I just get the login page over again, there is no errors in the apache logs, but I do have this in the json debug log:

======= 2011/11/22, 23:28:08 =======
Source IP: xx.xx.xx.xx
Action: user.authenticate
Request: 
'{"auth":false,"method":"user.authenticate","id":1,"params":{"user":"user","password":"pass"},"jsonrpc":"2.0"}'

Response: 
false

I have confirmed that the API is working using curl from the command line.  I have verified that my server has the requirements and is configured as shown on the install page.  

Thoughts?

**Comment by mattiasgeniar** [comment]
Interesting, do you know if this worked in Zabbix 1.8.6 or earlier? If so, I'll have to see what the authentication changes (may) have been.

**Comment by mattcadorette** [comment]
This is actually my first time using MoZBX, so I am not sure if it works with 1.8.6.

----- Original Message -----

**Comment by mattcadorette** [comment]
Resolved, Zabbix side config issue.
