### ISSUE TITLE
Wrong use of strlen() on getLastError()

### ISSUE THREAD

**Issue by lauer** [mattiasgeniar/MoZBX#3]
$zabbix->getLastError() returns an array, but strlen() is used. 

There is a patch to fix that problem

<pre>
diff --git a/index.php b/index.php
index 76fc4f7..b54cb10 100755
--- a/index.php
+++ b/index.php
@@ -245,7 +245,7 @@
                                <?php
                                        if (isset($_POST['zabbixUsername'])) {
                                                // POST variables set, but still showint the form. Invalid credentials?
-                                               if (strlen($zabbix->getLastError()) > 0) {
+                                               if (count($zabbix->getLastError()) > 0) {
                                                        $arrError = $zabbix->getLastError();
                                                        $errormsg = $arrError["data"];
                                                        //print_r($arrError);
</pre>

**Comment by mattiasgeniar** [comment]
You've already fixed this as well, will close it down. :)
