### ISSUE TITLE
"Home" button not working on Nokia N9 / Fennec

### ISSUE THREAD

**Issue by ZeiP** [mattiasgeniar/MoZBX#32]
I'm using Nokia N9 with Fennec browser. When I go to Active Triggers, the Home button in the upper left corner only reads ”me” (so the first part of the word disappears somewhere) and when I click it, it shows only briefly the home page and then returns to the Active Triggers page. 

The browser window also contains some whitespace (about 40 % of the screen width) to the right; the interface itself shows correctly, but "scrolling" to right show the whitespace before the browser interface functionality. 

Hope someone would figure out why the browser doesn't stay on the home page; the other two things are just small glitches :)  It's looking very promising, thanks!

**Comment by mattiasgeniar** [comment]
Re-did the entire UI, shouldn't be an issue anymore, please pull the latest version once it's pushed in a few days
