### ISSUE TITLE
mozbx not working with zabbix 2.0.4

### ISSUE THREAD

**Issue by echampet** [mattiasgeniar/MoZBX#36]
Hi

i haven't had time to investigate but it seems that updating from zabbix 2.0.3 to 2.0.4 break mozbx (the graphs images doesn't show up anymore)

edit: problem is comming from the version check ($this->getVersion() == '1.4')

Thanks for MozBX

**Comment by echampet** [comment]
```
======= 2013/01/11, 18:33:13 =======
Source IP: aaa.bbb.ccc.ddd
API URL: https://sv1.lyoncapitale.fr/zabbix/api_jsonrpc.php
Action: apiinfo.version
Request: 
'{"auth":"aaaaaaaaaaaaaaaaaaaaa","method":"apiinfo.version","id":1,"params":[],"jsonrpc":"2.0"}'

Response: 
'{"jsonrpc":"2.0","result":"2.0.4","id":1}'
=======
```

**Comment by mattiasgeniar** [comment]
Thanks for the report, since 2.0.4 the Zabbix API version matches the Zabbix version (where this used to differ). I know the fix, will implement later this weekend.

**Comment by mattiasgeniar** [comment]
If you grab the latest release, that should fix it. Thanks for reporting!
