### ISSUE TITLE
Login fails when running MoZBX on own server and promptCredentials is false

### ISSUE THREAD

**Issue by drianpauL** [mattiasgeniar/MoZBX#39]
When running MoZBX 0.5 on our own server with these config variables (in our own config.php):
- $arrSettings["isHosted"] = true;
- $arrSettings["promptCredentials"] = false;
  ... the [automatic login in index.php](https://github.com/mattiasgeniar/MoZBX/blob/4ec49d42/index.php#L12-L15) does not work and drops the user back to the login screen.

This is because of the way the main $zabbix object is [constructed in class_zabbix.php when initialised from the $arrSettings](https://github.com/mattiasgeniar/MoZBX/blob/4ec49d42/class_zabbix.php#L70-L79), it does not append "api_jsonrpc.php" to the $this->zabbix_url variable like it does with respective PHP scripts for $this->zabbix_url_graph and $this->zabbix_url_index

Will submit a pull request for the minor fix I made to get it to work in our environment.

**Comment by drianpauL** [comment]
Pull request submitted - https://github.com/mattiasgeniar/MoZBX/pull/40

**Comment by mattiasgeniar** [comment]
Your fix indeed solves this, thank you for the pull request!
